### ISSUE TITLE
"Duplicate" Records

### ISSUE THREAD

**Issue by mgob** [SaaShup/netbox-cloudflare-plugin#4]
| Netbox version | Plugin Version | Agent version |  Docker API Version |
| 4.0.10 | 0.2.0 |  |  |
|  |  |  |  |

## Actual Behavior
When attempting to add a zone, we get the following error, and it appears to be for a record that has two A-records, such as when a round-robin is used.  Different values ( different IPs in this case, an A-Record ) but same key.

![Screenshot 2024-08-29 at 11 56 50 AM](https://github.com/user-attachments/assets/d7d2ddb8-8ad0-481e-8b80-7f8926fe08d6)

## Desired Behavior

Add the round robin records.

I haven't dug into anything yet but it looks like that name value has to be unique which would make it impossible to have round robin records.

Cheers!

**Comment by lvenier** [comment]
@mgob Thanks for your issue.

@fanshan I have checked and it is possible to have DNS round robin in cloudflare (surprisingly).
We would need to change the unicity from the (name) to (name,content)
